spring.application.name=Journal App

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://kumariananta01_db_user:5EtkQJEss8KJs0cj@cluster0.7ozpzb7.mongodb.net/journaldb?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=
#spring.data.mongodb.password=

